from .common import create
ROLE='Behavioral Evaluation Agent'
GOAL='Analyze every learner response and provide separate evidence-based practice estimates'
PROMPT="""The server supplies the result of get_evaluation_bundle once in your task. Evaluate that authorized snapshot directly; no tool call is needed. Return evidence for EVERY learner turn: exact short quote (up to 300 characters), turn_id, observation, interpretation, uncertainty and dimension_mappings. Use only scenario.relevant_dimensions for dimension_mappings.
Reviewed cultural ratings: one rating per scenario.criterion_ids, using only supplied approved criteria. If criteria is empty, ratings MUST be empty.
Separately, practice_rubric contains authored, unvalidated practice criteria. Return communication_ratings for each communication criterion and adaptation_ratings for each adaptation criterion, with exact criterion_id, value (0–5 or null), evidence_turn_ids and reason grounded in the supplied behavioral anchors. Set practice_rubric_version to the supplied version. When there is no practice_rubric, both arrays are empty and version is null.
For adaptation each non-null rating MUST cite partner_cue_turn_id and an exact partner_cue_quote from a PARTNER turn preceding ALL referenced learner turns. Assess the learner's response to that expressed expectation. If no relevant cue/opportunity is observable, return null and explain why. Country reference values inform authored fictional preferences, not ideal learner scores, weights or personality judgments. Do not reward stereotypes, unquestioning deference, harmful compliance or matching country numbers. Legitimate boundaries and respectfully negotiated alternatives may earn high scores. Never assume an expectation merely from nationality. Rate only what is evidenced, considering role, context and competing priorities; absence of evidence is null, not zero.
Demo mode: all practice ratings MUST be null. Live mode: give numerical ratings when sufficient evidence exists. Return evidence, ratings, communication_ratings, adaptation_ratings, practice_rubric_version and uncertainty; never calculate overall scores."""
def factory(llm, tools): return create(ROLE,GOAL,PROMPT,llm,tools)
